### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wneessen** [wneessen/arrgo#46]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7cd96f]
goroutine 3429 [running]:
github.com/wneessen/arrgo/bot.(*Bot).SlashCmdSoTBalance(0xc00012c0c0, 0xc0002e25a0?, 0xc000>
/builddir/bot/sc_handler_sot_userstats.go:112 +0x4f
github.com/wneessen/arrgo/bot.(*Bot).SlashCommandHandler(0xc00012c0c0, 0x0?, 0xc000012150)
/builddir/bot/slashcmd.go:400 +0x1395
github.com/bwmarrin/discordgo.interactionCreateEventHandler.Handle(0x0?, 0x0?, {0x845b40?, >
/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.0/eventhandlers.go:693 +0x38
created by github.com/bwmarrin/discordgo.(*Session).handle
/go/pkg/mod/github.com/bwmarrin/discordgo@v0.27.0/event.go:171 +0x16a
```

**Comment by wneessen** [comment]
Fixed with 703b705fc0827aa4542a1fc7d6e24b8d94f045aa
